# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb_spring
spring.datasource.username=postgres
spring.datasource.password=password

#this is for exception handler
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

server.address=localhost
server.port=8080
# JPA + Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
# ===============================
# ? JWT Configuration
# ===============================
# App Properties

demo.app.jwtSecret= ==================imthegreatmagicianhaha========================
demo.app.jwtExpirationMs=86400000


#thi is for reload

spring.devtools.restart.additional-paths=src/main/java

#logs for jpa
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE